<a href="https://colab.research.google.com/github/serjduvk/Homework/blob/master/%D0%9B%D0%B5%D0%BA%D1%86%D0%B8%D1%8F_7_%D0%94%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D1%8F%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_%22HW_7_lesson_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание к 7 уроку.

**Дедлайн: 23.12.2020**

colab: https://colab.research.google.com/drive/1KLD5pDCa0ka_g1U4D2ExihaaEwXzfTPW?usp=sharing

**ФОРМАТ ОТЧЕТНОСТИ:** pdf-файл с решенными задачами (задачи 2-9), ноутбук с проверкой решения этих задач (при помощи numpy), и pdf файл с отчетом по 1-ой задаче (краткий пересказ статьи). Вы можете оформить решения с использованием Markdown (писать текст прямо в юпитер ноутбуке), Latex, Word или же решить в тетради и сформировать pdf из фото.

Итого: 2 pdf файла.

Все задания необходимо выполнять ВРУЧНУЮ. А также проверить корректность полученных результатов с использованием Numpy.

Туториал как писать "Latex-формулы" прямо в Юпитере:
https://www.youtube.com/watch?v=vSc25kdgecg

Ноутбук с примером формул: https://nbviewer.jupyter.org/github/postlogist/course_opt/blob/master/jupyter_tutorial/02_markdown.ipynb


## Пример


Найдем ранг матрицы 

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26\\ 
5 & 14 & 22 & 31 & 40
\end{pmatrix}.$$

Четвертая строка является суммой второй и третьей строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26
\end{pmatrix}.$$

Из второй и третьей строк вычтем первую, умноженную на $2$ и $3$ соответственно:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 2 & 5 & 8 & 11
\end{pmatrix}.$$

И вычтем из третьей строки вторую, умноженную на $2$:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 0 & 1 & 2 & 3
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $3$.

In [ ]:
# Проверка

import numpy as np
a = [1, 2, 3, 4, 5]
b = [2, 5, 8, 11, 14]
c = [3, 9, 14, 20, 26]
d = [5, 14, 22, 31, 40]

x = np.array([a, b, c, d])
r = np.linalg.matrix_rank(x)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3


# Задачи

**1.** Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

- Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.


__6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$


__7.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

# Доп материалы
1. [Способы задать матрицу в NumPy](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).
2. [numpy.transpose](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.transpose.html).
3. [array.T](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.T.html).
4. [Перемножение матриц в NumPy](https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).

5. [Определитель матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.det.html)

6. [Ранг матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.matrix_rank.html)

7. [Обращение матриц в NumPy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)

In [ ]:
import numpy as np


In [ ]:
Косинусное сходство — это мера сходства между двумя векторами пространства, которая используется для измерения косинуса угла между ними.

Мягкая косинусная мера 
Мягкий косинус или («мягкое» сходство) между двумя векторами учитывает сходство между парами объектов. 
Традиционное косинусное подобие рассматривает функции модели векторного пространства (VSM) как независимые или совершенно разные, 
в то время как мягкая косинусная мера предлагает учитывать сходство функций в VSM, что также помогает обобщить концепцию косинуса (и мягкого косинуса). 

In [ ]:
#Задание 2 
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица С = A + B\n{a + b}')
print(f'Матрица D = AB\n{np.dot(a, b)}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]
Матрица D = AB
[[  4 -11]
 [ 12  -3]]


In [ ]:
#Задание 3 Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию 3A−2B+4C .
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c= np.array([[2, -4], [1, 1]])
print(f'3A-2B+4C =\n{3*a-2*b+4*c}')

3A-2B+4C =
[[ 11  -5]
 [  9 -12]]


In [ ]:
#Задание 4
a = np.array([[4, 1], [5, -2],[2,3]])
b=a.T


print(f'Матрица:\n{a}')
print(f'Транспонированная матрица:\n{a.T}')
print(f'A*A transp \n {np.dot(a, b)}')
print(f'A transp *A \n {np.dot(b, a)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
A*A transp 
 [[17 18 11]
 [18 29  4]
 [11  4 13]]
A transp *A 
 [[45  0]
 [ 0 14]]


In [ ]:
#задание 5
n=int(input('Введите число строк в матрице A  '))
m=int(input('Введите число столбцов в матрице A  '))
a=[]
b=[]
for i in range(n):
    for j in range(m):
        x=int(input('Введите элемент матрицы A  '))
        a.append(x)
A=np.reshape(a, (n, m))
n2=int(input('Введите число строк в матрице B  '))
m2=int(input('Введите число столбцов в матрице B  '))
a=[]
for i in range(n2):
    for j in range(m2):
        x=int(input('Введите элемент матрицы B  '))
        a.append(x)
B=np.reshape(a, (n2, m2))
print(f'Матрица A:\n{A}')
print(f'Матрица B:\n{B}')

Введите число строк в матрице A  2
Введите число столбцов в матрице A  3
Введите элемент матрицы A  4
Введите элемент матрицы A  5
Введите элемент матрицы A  7
Введите элемент матрицы A  8
Введите элемент матрицы A  9
Введите элемент матрицы A  7
Введите число строк в матрице B  3
Введите число столбцов в матрице B  2
Введите элемент матрицы B  2
Введите элемент матрицы B  6
Введите элемент матрицы B  4
Введите элемент матрицы B  8
Введите элемент матрицы B  7
Введите элемент матрицы B  6
Матрица A:
[[4 5 7]
 [8 9 7]]
Матрица B:
[[2 6]
 [4 8]
 [7 6]]


In [ ]:
C=np.zeros((n,m2))
if m==n2:
    for i in range(n):
        for j in range(m2):
            for k in range(n2):
                C[i][j] += A[i][k] * B[k][j]
    print('Результат перемножения матриц A B:')
    for r in C:
      print(r)                
else:
    print('матрицы нельзя перемножить')

Результат перемножения матриц A B:
[ 77. 106.]
[101. 162.]


In [ ]:
#задание 6
a = np.array([[np.sin(x),-np.cos(x)], [np.cos(x),np.sin(x)]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[-0.2794155  -0.96017029]
 [ 0.96017029 -0.2794155 ]]
Определитель:
1


In [ ]:
a = np.array([[8,4,6], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[8 4 6]
 [0 5 1]
 [0 0 9]]
Определитель:
360


In [ ]:
a = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Определитель:
0


In [ ]:
#Задание 8 Если определитель матрицы равен 0, то матрица вырожденная 
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


In [ ]:
#Задание 9
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы: {r}')


Ранг матрицы: 2


In [ ]:
a = np.array([[0, 0, 2,1], [0, 0, 2,2], [2, 3, 5,6]])
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
